# Site settings
title: Data Handling and Visualisation in R (BMS109 Introduction to Biomedical Science)
session: 2019-2020
email: m.milo@sheffield.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  Data handling and visualisation in R for Biomedical Science students.
baseurl: "/R_data_handling" # the subpath of your site, e.g. /blog/
url: "http://opendsi.cc" # the base hostname & protocol for your site
twitter_username: marta_milo
github_username:  martamilo
banner: about_image.jpg
# Build settings
markdown: kramdown
disqus: opendsiccbioinformatics
comments: true

analytics:
  google:
    tracking_id: UA-62964644-1
